name: Devel Unit Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test BoringGames Core
      run: dotnet test --no-restore --verbosity normal /home/runner/work/BoringGames/BoringGames/BoringGames.Core.Test/BoringGames.Core.Test.csproj
    - name: Test BoringGames Shared
      run: dotnet test --no-restore --verbosity normal /home/runner/work/BoringGames/BoringGames/BoringGames.Shared.Test/BoringGames.Shared.Test.csproj
    - name: Test TicTacToe
      run: dotnet test --no-restore --verbosity normal /home/runner/work/BoringGames/BoringGames/TicTacToe.Test/TicTacToe.Test.csproj
    - name: Test BoringGames Text
      run: dotnet test --no-restore --verbosity normal /home/runner/work/BoringGames/BoringGames/BoringGames.Txt.Test/BoringGames.Txt.Test.csproj
    - name: Test BoringGames Api
      run: dotnet test --no-restore --verbosity normal /home/runner/work/BoringGames/BoringGames/BoringGames.Api.Test/BoringGames.Api.Test.csproj
